// WEKA KEYS ZAKO ZA KUSAVE DATA KWENYE LOCAL STORAGE HAPA ILI HATA UKIBADILI
// ISIKUPE SHIDA ULIKO TUMIA RATHER THAN HARDCODING KEYS WAKATI UNAZITUMIA

class FlutterSecureStorageKeys {
  static const authResponse = 'AUTH_RESPONSE';
  static const themeKey = 'USER_THEME_MODE';
  static const languageLocale = 'USER_LANGUAGE_MODE';
  static const isFirstAppLaunch = "APP_LAUNCHED_FOR_FIRST_TIME_AFTER_DOWNLOAD";
}
